Docker: Updated to latest dev dependencies and improved build reproducability

diff --git a/dev-up/ionic2-up/Dockerfile b/dev-up/ionic2-up/Dockerfile
--- a/dev-up/ionic2-up/Dockerfile
+++ b/dev-up/ionic2-up/Dockerfile
@@ -1,4 +1,4 @@
-FROM java:openjdk-8u72-jdk
+FROM java:openjdk-8u102-jdk
 
 MAINTAINER darren@hotshots.xyz
 LABEL version="1.0"
@@ -7,52 +7,69 @@ LABEL github="https://github.com/Hotshotsteam/ionic2-up"
 
 ENV LANG C.UTF-8
 
-RUN curl -sL https://deb.nodesource.com/setup_6.x | bash -
+ADD ./sources.list /etc/apt/sources.list
+
+ENV ANDROID_SDK_URL="https://dl.google.com/android/android-sdk_r24.4.1-linux.tgz" \
+    ANDROID_BUILD_TOOLS_VERSION=23.0.3 \
+    ANDROID_APIS="android-10,android-15,android-16,android-17,android-18,android-19,android-20,android-21,android-22,android-23,android-24" \
+    ANT_HOME="/usr/share/ant" \
+    MAVEN_HOME="/usr/share/maven" \
+    GRADLE_HOME="/usr/share/gradle" \
+    ANDROID_HOME="/opt/android-sdk-linux"
+
+ENV PATH $PATH:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools:$ANDROID_HOME/build-tools/$ANDROID_BUILD_TOOLS_VERSION:$ANT_HOME/bin:$MAVEN_HOME/bin:$GRADLE_HOME/bin
 
 RUN apt-get update && apt-get install -y --no-install-recommends \
-      nodejs \
-      unzip \
-      lib32z1 \
-      lib32ncurses5 \
-      lib32stdc++6 \
-    && apt-get clean && \
-    rm -rf /var/lib/apt/lists/*
+    curl \
+    ant \
+    gradle \
+    lib32ncurses5 \
+    lib32stdc++6 \
 
-RUN mkdir $HOME/install && \
-    ANDROID_HOME=$HOME/android && \
-    SDK='https://dl.google.com/android/repository' && \
-    echo \
-      http://dl.google.com/android/android-sdk_r24.4.1-linux.tgz \
-      $SDK/platform-tools_r23.1.0-linux.zip \
-      $SDK/tools_r25.1.6-linux.zip \
-      $SDK/build-tools_r23.0.3-linux.zip \
-      | tr " " "\n" \
-      | wget -q -P $HOME/install -i - && \
-    tar zxvf $HOME/install/android-sdk_r24.4.1-linux.tgz -C $HOME/install && \
-    mv $HOME/install/android-sdk-linux $ANDROID_HOME && \
-    rm -Rf $ANDROID_HOME/tools && \
-    mkdir -p $ANDROID_HOME/build-tools && \
-    mkdir -p $ANDROID_HOME/platforms && \
-    unzip "$HOME/install/*.zip" -d $ANDROID_HOME && \
-    mv $ANDROID_HOME/android-6.0 $ANDROID_HOME/build-tools/23.0.3 && \
-    wget -q $SDK/platform-23_r03.zip -P $HOME/install && \
-    unzip $HOME/install/platform-23_r03.zip -d $ANDROID_HOME && \
-    mv $ANDROID_HOME/android-6.0 $ANDROID_HOME/platforms/android-23 && \
-    rm -Rf $HOME/install && \
-    printf \
-      "\nANDROID_HOME=\$HOME/android\nPATH=\$PATH:\$ANDROID_HOME/platform-tools:\$ANDROID_HOME/tools\nexport ANDROID_HOME\n" \
-      >> $HOME/.bashrc
+  # Install Android SDK
+  && curl -sL ${ANDROID_SDK_URL} | tar xz -C /opt \
+  && echo y | android update sdk -a -u -t platform-tools,${ANDROID_APIS},build-tools-${ANDROID_BUILD_TOOLS_VERSION} \
+  && chmod a+x -R $ANDROID_HOME \
+  && chown -R root:root $ANDROID_HOME \
+
+  # Clean up
+  && apt-get clean \
+  && apt-get autoremove -y \
+  && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
 
 ADD ./70-android.rules /etc/udev/rules.d/70-android.rules
 
-ENV ANDROID_HOME /root/android
+# Install Node
+# RUN curl -sL https://deb.nodesource.com/setup_6.x | bash -
+# gpg keys listed at https://github.com/nodejs/node
+RUN set -ex \
+  && for key in \
+    9554F04D7259F04124DE6B476D5A82AC7E37093B \
+    94AE36675C464D64BAFA68DD7434390BDBE9B9C5 \
+    0034A06D9D9B0064CE8ADF6BF1747F4AD2306D93 \
+    FD3A5288F042B6850C66B31F09FE44734EB7990E \
+    71DCFD284A79C3B38668286BC97EC7A07EDE3FC1 \
+    DD8F2338BAE7501E3DD5AC78C273792F7D83545D \
+    B9AE9905FFD7803F25714661B63B535A4C206CA9 \
+    C4F0DFFF4E8C1A8236409D08E73BC641CC11F4C8 \
+  ; do \
+    gpg --keyserver ha.pool.sks-keyservers.net --recv-keys "$key"; \
+  done
 
-ENV PATH $ANDROID_HOME/platform-tools:$ANDROID_HOME/tools:$PATH
+ENV NPM_CONFIG_LOGLEVEL info
+ENV NODE_VERSION 6.7.0
 
-RUN npm install -g cordova
-RUN npm install -g typings
-RUN npm install -g tsc
-RUN npm install -g ionic@2.0.0-beta.30
+RUN curl -SLO "https://nodejs.org/dist/v$NODE_VERSION/node-v$NODE_VERSION-linux-x64.tar.xz" \
+  && curl -SLO "https://nodejs.org/dist/v$NODE_VERSION/SHASUMS256.txt.asc" \
+  && gpg --batch --decrypt --output SHASUMS256.txt SHASUMS256.txt.asc \
+  && grep " node-v$NODE_VERSION-linux-x64.tar.xz\$" SHASUMS256.txt | sha256sum -c - \
+  && tar -xJf "node-v$NODE_VERSION-linux-x64.tar.xz" -C /usr/local --strip-components=1 \
+  && rm "node-v$NODE_VERSION-linux-x64.tar.xz" SHASUMS256.txt.asc SHASUMS256.txt \
+  && ln -s /usr/local/bin/node /usr/local/bin/nodejs
+
+# Install dependencies
+RUN npm install --save -g cordova typings tsc ionic
+RUN mkdir -p /root/.config/configstore && echo "{\"optOut\": \"true\"}" > /root/.config/configstore/insight-cordova.json
 
 WORKDIR /project
 
